#Mysql Settings
mySqlRootPass: password
mySqlKamailioUser: kamailiouser
mySqlKamailioPass: password
mySqlHost: "192.168.120.79"
mySqlBindIP: "{{mySqlHost}}"

#Allowed IP addresses to be connected to remote MySQL server
#FIXME:: These IP addresses should be inferred automatically. Anyway creating Kamailio's DB using two hosts will cause problems.
kam1IP: "192.168.120.66"
kam2IP: "192.168.120.76"


#Kamailio-related settings
kamailioSrcPath: /usr/local/src/kamailio
kamailioHomeDir: /var/run/kamailio
kamailioDbURL: mysql://{{mySqlKamailioUser}}:{{mySqlKamailioPass}}@{{mySqlHost}}/kamailio
kamailioSourceUrl: http://www.kamailio.org/pub/kamailio/4.1.1/src/kamailio-4.1.1_src.tar.gz
kamailioVirtualIP: "192.168.120.90"
kamailioVirtualIPNetMask: "255.255.255.0"
kamailioVirtualIPBroadCast: "192.168.120.255"
kamailioPublicIP: "192.168.120.90"
kamailioSIPDomain: "{{kamailioPublicIP}}"


#Other
preferencesPath: /etc/apt/preferences.d/
mtCastAddr: "239.0.0.95"

#RTPProxy related settings
# If you want to deploy with a cluster of rtpproxy servers set this variable to True and set rtpproxy server informations using rtpServers array.
# Otherwise each node in the cluster will have it's own local rtpproxy server.
withRTPProxyCluster: False  
#This is an array that contains a list of entries that will automatically added to rtpproxy's database
#Each item must be of the form ip:port.
rtpHostsInfo: 
    - 192.168.120.55:7722
rtpProxyDBURL: mysql://root:password@192.168.120.79/rtpproxy


#CIB
cibPath: "/usr/local/src/"